// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Torneio.Infrastructure.Data;

#nullable disable

namespace Torneio.Infrastructure.Migrations
{
    [DbContext(typeof(TorneioDbContext))]
    [Migration("20260428145622_AddExibicaoPublicaListaPesquisaTorneio")]
    partial class AddExibicaoPublicaListaPesquisaTorneio
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Torneio.Domain.Entities.AdminGeral", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("senha_hash");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("usuario");

                    b.HasKey("Id")
                        .HasName("pk_admins_geral");

                    b.HasIndex("Usuario")
                        .IsUnique()
                        .HasDatabaseName("ix_admins_geral_usuario");

                    b.ToTable("admins_geral", (string)null);
                });

            modelBuilder.Entity("Torneio.Domain.Entities.AdminTorneio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("DeveAlterarSenha")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("deve_alterar_senha");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("senha_hash");

                    b.Property<Guid>("TorneioId")
                        .HasColumnType("uuid")
                        .HasColumnName("torneio_id");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("usuario");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("pk_admins_torneio");

                    b.HasIndex("TorneioId")
                        .HasDatabaseName("ix_admins_torneio_torneio_id");

                    b.HasIndex("Usuario", "TorneioId")
                        .IsUnique()
                        .HasDatabaseName("ix_admins_torneio_usuario_torneio_id");

                    b.ToTable("admins_torneio", (string)null);
                });

            modelBuilder.Entity("Torneio.Domain.Entities.Banner", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<string>("Destino")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("destino");

                    b.Property<string>("ImagemUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("imagem_url");

                    b.Property<int>("Ordem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("ordem");

                    b.Property<int>("TipoDestino")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("tipo_destino");

                    b.Property<Guid>("TorneioId")
                        .HasColumnType("uuid")
                        .HasColumnName("torneio_id");

                    b.HasKey("Id")
                        .HasName("pk_banners");

                    b.HasIndex("TorneioId")
                        .HasDatabaseName("ix_banners_torneio_id");

                    b.HasIndex("Ativo", "Ordem")
                        .HasDatabaseName("ix_banners_ativo_ordem");

                    b.ToTable("banners", (string)null);
                });

            modelBuilder.Entity("Torneio.Domain.Entities.Captura", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_hora");

                    b.Property<Guid>("EquipeId")
                        .HasColumnType("uuid")
                        .HasColumnName("equipe_id");

                    b.Property<int?>("FonteFoto")
                        .HasColumnType("integer")
                        .HasColumnName("fonte_foto");

                    b.Property<string>("FotoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("foto_url");

                    b.Property<bool>("Invalidada")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("invalidada");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("item_id");

                    b.Property<Guid>("MembroId")
                        .HasColumnType("uuid")
                        .HasColumnName("membro_id");

                    b.Property<string>("MotivoInvalidacao")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("motivo_invalidacao");

                    b.Property<int>("Origem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("origem");

                    b.Property<bool>("PendenteSync")
                        .HasColumnType("boolean")
                        .HasColumnName("pendente_sync");

                    b.Property<decimal>("TamanhoMedida")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("tamanho_medida");

                    b.Property<Guid>("TorneioId")
                        .HasColumnType("uuid")
                        .HasColumnName("torneio_id");

                    b.HasKey("Id")
                        .HasName("pk_capturas");

                    b.HasIndex("EquipeId")
                        .HasDatabaseName("ix_capturas_equipe_id");

                    b.HasIndex("ItemId")
                        .HasDatabaseName("ix_capturas_item_id");

                    b.HasIndex("MembroId")
                        .HasDatabaseName("ix_capturas_membro_id");

                    b.HasIndex("PendenteSync")
                        .HasDatabaseName("ix_capturas_pendente_sync");

                    b.HasIndex("TorneioId", "EquipeId")
                        .HasDatabaseName("ix_capturas_torneio_id_equipe_id");

                    b.HasIndex("TorneioId", "MembroId")
                        .HasDatabaseName("ix_capturas_torneio_id_membro_id");

                    b.ToTable("capturas", (string)null);
                });

            modelBuilder.Entity("Torneio.Domain.Entities.ChecklistTorneioItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Concluido")
                        .HasColumnType("boolean")
                        .HasColumnName("concluido");

                    b.Property<DateTime?>("Data")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data");

                    b.Property<string>("Item")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("item");

                    b.Property<string>("Responsavel")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("responsavel");

                    b.Property<Guid>("TorneioId")
                        .HasColumnType("uuid")
                        .HasColumnName("torneio_id");

                    b.HasKey("Id")
                        .HasName("pk_checklist_torneio_itens");

                    b.ToTable("checklist_torneio_itens", (string)null);
                });

            modelBuilder.Entity("Torneio.Domain.Entities.CustoTorneio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Categoria")
                        .HasColumnType("integer")
                        .HasColumnName("categoria");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("descricao");

                    b.Property<string>("Observacao")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("observacao");

                    b.Property<decimal>("Quantidade")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("quantidade");

                    b.Property<string>("Responsavel")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("responsavel");

                    b.Property<Guid>("TorneioId")
                        .HasColumnType("uuid")
                        .HasColumnName("torneio_id");

                    b.Property<decimal>("ValorTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("valor_total");

                    b.Property<decimal>("ValorUnitario")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("valor_unitario");

                    b.Property<DateTime?>("Vencimento")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("vencimento");

                    b.HasKey("Id")
                        .HasName("pk_custos_torneio");

                    b.ToTable("custos_torneio", (string)null);
                });

            modelBuilder.Entity("Torneio.Domain.Entities.DoacaoPatrocinador", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<DateTime>("DataDoacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_doacao");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descricao");

                    b.Property<string>("NomePatrocinador")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome_patrocinador");

                    b.Property<string>("Observacao")
                        .HasColumnType("text")
                        .HasColumnName("observacao");

                    b.Property<Guid?>("PatrocinadorId")
                        .HasColumnType("uuid")
                        .HasColumnName("patrocinador_id");

                    b.Property<decimal?>("Quantidade")
                        .HasColumnType("numeric")
                        .HasColumnName("quantidade");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer")
                        .HasColumnName("tipo");

                    b.Property<Guid>("TorneioId")
                        .HasColumnType("uuid")
                        .HasColumnName("torneio_id");

                    b.Property<decimal?>("Valor")
                        .HasColumnType("numeric")
                        .HasColumnName("valor");

                    b.HasKey("Id")
                        .HasName("pk_doacoes_patrocinadores");

                    b.ToTable("doacoes_patrocinadores", (string)null);
                });

            modelBuilder.Entity("Torneio.Domain.Entities.Equipe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Capitao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("capitao");

                    b.Property<decimal>("Custo")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("custo");

                    b.Property<DateTime?>("DataVencimentoCusto")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_vencimento_custo");

                    b.Property<string>("FotoCapitaoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("foto_capitao_url");

                    b.Property<string>("FotoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("foto_url");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome");

                    b.Property<int>("QtdVagas")
                        .HasColumnType("integer")
                        .HasColumnName("qtd_vagas");

                    b.Property<int>("StatusFinanceiro")
                        .HasColumnType("integer")
                        .HasColumnName("status_financeiro");

                    b.Property<Guid>("TorneioId")
                        .HasColumnType("uuid")
                        .HasColumnName("torneio_id");

                    b.HasKey("Id")
                        .HasName("pk_equipes");

                    b.HasIndex("TorneioId")
                        .HasDatabaseName("ix_equipes_torneio_id");

                    b.ToTable("equipes", (string)null);
                });

            modelBuilder.Entity("Torneio.Domain.Entities.EspeciePeixe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("FotoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("foto_url");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome");

                    b.Property<string>("NomeCientifico")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("nome_cientifico");

                    b.HasKey("Id")
                        .HasName("pk_especies_peixe");

                    b.ToTable("especies_peixe", (string)null);
                });

            modelBuilder.Entity("Torneio.Domain.Entities.Fiscal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("DeveAlterarSenha")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("deve_alterar_senha");

                    b.Property<string>("FotoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("foto_url");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("senha_hash");

                    b.Property<Guid>("TorneioId")
                        .HasColumnType("uuid")
                        .HasColumnName("torneio_id");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("usuario");

                    b.HasKey("Id")
                        .HasName("pk_fiscais");

                    b.HasIndex("TorneioId")
                        .HasDatabaseName("ix_fiscais_torneio_id");

                    b.HasIndex("Usuario", "TorneioId")
                        .IsUnique()
                        .HasDatabaseName("ix_fiscais_usuario_torneio_id");

                    b.ToTable("fiscais", (string)null);
                });

            modelBuilder.Entity("Torneio.Domain.Entities.FiscalEquipe", b =>
                {
                    b.Property<Guid>("FiscalId")
                        .HasColumnType("uuid")
                        .HasColumnName("fiscal_id");

                    b.Property<Guid>("EquipeId")
                        .HasColumnType("uuid")
                        .HasColumnName("equipe_id");

                    b.HasKey("FiscalId", "EquipeId")
                        .HasName("pk_fiscal_equipe");

                    b.HasIndex("EquipeId")
                        .HasDatabaseName("ix_fiscal_equipe_equipe_id");

                    b.ToTable("fiscal_equipe", (string)null);
                });

            modelBuilder.Entity("Torneio.Domain.Entities.Grupo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome");

                    b.Property<Guid>("TorneioId")
                        .HasColumnType("uuid")
                        .HasColumnName("torneio_id");

                    b.HasKey("Id")
                        .HasName("pk_grupos");

                    b.HasIndex("TorneioId")
                        .HasDatabaseName("ix_grupos_torneio_id");

                    b.HasIndex("TorneioId", "Nome")
                        .IsUnique()
                        .HasDatabaseName("ix_grupos_torneio_id_nome");

                    b.ToTable("grupos", (string)null);
                });

            modelBuilder.Entity("Torneio.Domain.Entities.GrupoMembro", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("GrupoId")
                        .HasColumnType("uuid")
                        .HasColumnName("grupo_id");

                    b.Property<Guid>("MembroId")
                        .HasColumnType("uuid")
                        .HasColumnName("membro_id");

                    b.HasKey("Id")
                        .HasName("pk_grupos_membros");

                    b.HasIndex("MembroId")
                        .HasDatabaseName("ix_grupos_membros_membro_id");

                    b.HasIndex("GrupoId", "MembroId")
                        .IsUnique()
                        .HasDatabaseName("ix_grupos_membros_grupo_id_membro_id");

                    b.ToTable("grupos_membros", (string)null);
                });

            modelBuilder.Entity("Torneio.Domain.Entities.Item", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal?>("Comprimento")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("comprimento");

                    b.Property<Guid>("EspeciePeixeId")
                        .HasColumnType("uuid")
                        .HasColumnName("especie_peixe_id");

                    b.Property<decimal>("FatorMultiplicador")
                        .HasColumnType("numeric(10,4)")
                        .HasColumnName("fator_multiplicador");

                    b.Property<Guid>("TorneioId")
                        .HasColumnType("uuid")
                        .HasColumnName("torneio_id");

                    b.HasKey("Id")
                        .HasName("pk_itens");

                    b.HasIndex("EspeciePeixeId")
                        .HasDatabaseName("ix_itens_especie_peixe_id");

                    b.HasIndex("TorneioId")
                        .HasDatabaseName("ix_itens_torneio_id");

                    b.ToTable("itens", (string)null);
                });

            modelBuilder.Entity("Torneio.Domain.Entities.LogAuditoria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Acao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("acao");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("categoria");

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_hora");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("descricao");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("ip_address");

                    b.Property<string>("NomeTorneio")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome_torneio");

                    b.Property<Guid?>("TorneioId")
                        .HasColumnType("uuid")
                        .HasColumnName("torneio_id");

                    b.Property<string>("UsuarioNome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("usuario_nome");

                    b.Property<string>("UsuarioPerfil")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("usuario_perfil");

                    b.HasKey("Id")
                        .HasName("pk_logs");

                    b.HasIndex("Categoria")
                        .HasDatabaseName("ix_logs_categoria");

                    b.HasIndex("DataHora")
                        .HasDatabaseName("ix_logs_data_hora");

                    b.HasIndex("TorneioId")
                        .HasDatabaseName("ix_logs_torneio_id");

                    b.ToTable("logs", (string)null);
                });

            modelBuilder.Entity("Torneio.Domain.Entities.Membro", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Celular")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("celular");

                    b.Property<bool>("DeveAlterarSenha")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("deve_alterar_senha");

                    b.Property<string>("FotoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("foto_url");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome");

                    b.Property<string>("SenhaHash")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("senha_hash");

                    b.Property<string>("TamanhoCamisa")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tamanho_camisa");

                    b.Property<Guid>("TorneioId")
                        .HasColumnType("uuid")
                        .HasColumnName("torneio_id");

                    b.Property<string>("Usuario")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("usuario");

                    b.HasKey("Id")
                        .HasName("pk_membros");

                    b.HasIndex("TorneioId", "Usuario")
                        .IsUnique()
                        .HasDatabaseName("ix_membros_torneio_id_usuario");

                    b.ToTable("membros", (string)null);
                });

            modelBuilder.Entity("Torneio.Domain.Entities.ParcelaTorneio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Bonificada")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("bonificada");

                    b.Property<string>("ComprovanteContentType")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("comprovante_content_type");

                    b.Property<DateTime?>("ComprovanteDataUpload")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("comprovante_data_upload");

                    b.Property<string>("ComprovanteNomeArquivo")
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)")
                        .HasColumnName("comprovante_nome_arquivo");

                    b.Property<string>("ComprovanteUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("comprovante_url");

                    b.Property<string>("ComprovanteUsuarioNome")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("comprovante_usuario_nome");

                    b.Property<DateTime?>("DataPagamento")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_pagamento");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("descricao");

                    b.Property<Guid?>("DoacaoPatrocinadorId")
                        .HasColumnType("uuid")
                        .HasColumnName("doacao_patrocinador_id");

                    b.Property<Guid>("MembroId")
                        .HasColumnType("uuid")
                        .HasColumnName("membro_id");

                    b.Property<string>("MotivoBonificacao")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("motivo_bonificacao");

                    b.Property<int>("NumeroParcela")
                        .HasColumnType("integer")
                        .HasColumnName("numero_parcela");

                    b.Property<string>("Observacao")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("observacao");

                    b.Property<bool>("Pago")
                        .HasColumnType("boolean")
                        .HasColumnName("pago");

                    b.Property<Guid?>("ReferenciaId")
                        .HasColumnType("uuid")
                        .HasColumnName("referencia_id");

                    b.Property<string>("TipoParcela")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("tipo_parcela");

                    b.Property<Guid>("TorneioId")
                        .HasColumnType("uuid")
                        .HasColumnName("torneio_id");

                    b.Property<decimal>("Valor")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("valor");

                    b.Property<DateTime>("Vencimento")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("vencimento");

                    b.Property<bool>("VencimentoEditadoManual")
                        .HasColumnType("boolean")
                        .HasColumnName("vencimento_editado_manual");

                    b.HasKey("Id")
                        .HasName("pk_parcelas_torneio");

                    b.HasIndex("TorneioId", "MembroId", "TipoParcela", "NumeroParcela", "ReferenciaId")
                        .IsUnique()
                        .HasDatabaseName("ix_parcelas_torneio_torneio_id_membro_id_tipo_parcela_numero_p");

                    b.ToTable("parcelas_torneio", (string)null);
                });

            modelBuilder.Entity("Torneio.Domain.Entities.Patrocinador", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("ExibirNaTelaInicial")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("exibir_na_tela_inicial");

                    b.Property<bool>("ExibirNosRelatorios")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("exibir_nos_relatorios");

                    b.Property<string>("Facebook")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("facebook");

                    b.Property<string>("FotoUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("foto_url");

                    b.Property<string>("Instagram")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("instagram");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome");

                    b.Property<string>("Site")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("site");

                    b.Property<Guid>("TorneioId")
                        .HasColumnType("uuid")
                        .HasColumnName("torneio_id");

                    b.Property<string>("Zap")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("zap");

                    b.HasKey("Id")
                        .HasName("pk_patrocinadores");

                    b.HasIndex("TorneioId")
                        .HasDatabaseName("ix_patrocinadores_torneio_id");

                    b.ToTable("patrocinadores", (string)null);
                });

            modelBuilder.Entity("Torneio.Domain.Entities.Premio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("descricao");

                    b.Property<int>("Posicao")
                        .HasColumnType("integer")
                        .HasColumnName("posicao");

                    b.Property<Guid>("TorneioId")
                        .HasColumnType("uuid")
                        .HasColumnName("torneio_id");

                    b.HasKey("Id")
                        .HasName("pk_premios");

                    b.HasIndex("TorneioId", "Posicao")
                        .IsUnique()
                        .HasDatabaseName("ix_premios_torneio_id_posicao");

                    b.ToTable("premios", (string)null);
                });

            modelBuilder.Entity("Torneio.Domain.Entities.ProdutoExtraMembro", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<Guid>("MembroId")
                        .HasColumnType("uuid")
                        .HasColumnName("membro_id");

                    b.Property<string>("Observacao")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("observacao");

                    b.Property<Guid>("ProdutoExtraTorneioId")
                        .HasColumnType("uuid")
                        .HasColumnName("produto_extra_torneio_id");

                    b.Property<decimal>("Quantidade")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("quantidade");

                    b.Property<Guid>("TorneioId")
                        .HasColumnType("uuid")
                        .HasColumnName("torneio_id");

                    b.Property<decimal>("ValorCobrado")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("valor_cobrado");

                    b.HasKey("Id")
                        .HasName("pk_produtos_extras_membros");

                    b.HasIndex("TorneioId")
                        .HasDatabaseName("ix_produtos_extras_membros_torneio_id");

                    b.HasIndex("ProdutoExtraTorneioId", "MembroId")
                        .IsUnique()
                        .HasDatabaseName("ix_produtos_extras_membros_produto_extra_torneio_id_membro_id");

                    b.ToTable("produtos_extras_membros", (string)null);
                });

            modelBuilder.Entity("Torneio.Domain.Entities.ProdutoExtraTorneio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("Descricao")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("descricao");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome");

                    b.Property<Guid>("TorneioId")
                        .HasColumnType("uuid")
                        .HasColumnName("torneio_id");

                    b.Property<decimal>("Valor")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("valor");

                    b.HasKey("Id")
                        .HasName("pk_produtos_extras_torneio");

                    b.HasIndex("TorneioId")
                        .HasDatabaseName("ix_produtos_extras_torneio_torneio_id");

                    b.ToTable("produtos_extras_torneio", (string)null);
                });

            modelBuilder.Entity("Torneio.Domain.Entities.RegistroPublicoMembro", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Celular")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("celular");

                    b.Property<string>("CelularNormalizado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("celular_normalizado");

                    b.Property<DateTime?>("ConfirmadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("confirmado_em");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<DateTime>("ExpiraEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expira_em");

                    b.Property<Guid?>("MembroId")
                        .HasColumnType("uuid")
                        .HasColumnName("membro_id");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome");

                    b.Property<int>("QuantidadeEnvios")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("quantidade_envios");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("TamanhoCamisa")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tamanho_camisa");

                    b.Property<int>("TentativasValidacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("tentativas_validacao");

                    b.Property<Guid>("TorneioId")
                        .HasColumnType("uuid")
                        .HasColumnName("torneio_id");

                    b.Property<DateTime>("UltimoEnvioEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ultimo_envio_em");

                    b.HasKey("Id")
                        .HasName("pk_registros_publicos_membros");

                    b.HasIndex("TorneioId", "CelularNormalizado", "CriadoEm")
                        .HasDatabaseName("ix_registros_publicos_membros_torneio_id_celular_normalizado_c");

                    b.ToTable("registros_publicos_membros", (string)null);
                });

            modelBuilder.Entity("Torneio.Domain.Entities.SorteioEquipe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("EquipeId")
                        .HasColumnType("uuid")
                        .HasColumnName("equipe_id");

                    b.Property<Guid>("MembroId")
                        .HasColumnType("uuid")
                        .HasColumnName("membro_id");

                    b.Property<int>("Posicao")
                        .HasColumnType("integer")
                        .HasColumnName("posicao");

                    b.Property<Guid>("TorneioId")
                        .HasColumnType("uuid")
                        .HasColumnName("torneio_id");

                    b.HasKey("Id")
                        .HasName("pk_sorteios_equipe");

                    b.HasIndex("EquipeId")
                        .HasDatabaseName("ix_sorteios_equipe_equipe_id");

                    b.HasIndex("MembroId")
                        .HasDatabaseName("ix_sorteios_equipe_membro_id");

                    b.HasIndex("TorneioId")
                        .HasDatabaseName("ix_sorteios_equipe_torneio_id");

                    b.HasIndex("TorneioId", "MembroId")
                        .IsUnique()
                        .HasDatabaseName("ix_sorteios_equipe_torneio_id_membro_id");

                    b.ToTable("sorteios_equipe", (string)null);
                });

            modelBuilder.Entity("Torneio.Domain.Entities.SorteioGrupo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("EquipeId")
                        .HasColumnType("uuid")
                        .HasColumnName("equipe_id");

                    b.Property<Guid>("GrupoId")
                        .HasColumnType("uuid")
                        .HasColumnName("grupo_id");

                    b.Property<int>("Posicao")
                        .HasColumnType("integer")
                        .HasColumnName("posicao");

                    b.Property<Guid>("TorneioId")
                        .HasColumnType("uuid")
                        .HasColumnName("torneio_id");

                    b.HasKey("Id")
                        .HasName("pk_sorteios_grupo");

                    b.HasIndex("EquipeId")
                        .HasDatabaseName("ix_sorteios_grupo_equipe_id");

                    b.HasIndex("GrupoId")
                        .HasDatabaseName("ix_sorteios_grupo_grupo_id");

                    b.HasIndex("TorneioId")
                        .HasDatabaseName("ix_sorteios_grupo_torneio_id");

                    b.HasIndex("TorneioId", "EquipeId")
                        .IsUnique()
                        .HasDatabaseName("ix_sorteios_grupo_torneio_id_equipe_id");

                    b.HasIndex("TorneioId", "GrupoId")
                        .IsUnique()
                        .HasDatabaseName("ix_sorteios_grupo_torneio_id_grupo_id");

                    b.ToTable("sorteios_grupo", (string)null);
                });

            modelBuilder.Entity("Torneio.Domain.Entities.TorneioEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("ApenasMaiorCapturaPorPescador")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("apenas_maior_captura_por_pescador");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<string>("CorPrimaria")
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("cor_primaria");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<DateTime?>("DataPrimeiroVencimento")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_primeiro_vencimento");

                    b.Property<DateTime?>("DataTorneio")
                        .HasColumnType("date")
                        .HasColumnName("data_torneio");

                    b.Property<DateTime?>("DataVencimentoTaxaInscricao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_vencimento_taxa_inscricao");

                    b.Property<string>("Descricao")
                        .HasColumnType("text")
                        .HasColumnName("descricao");

                    b.Property<bool>("ExibirModuloFinanceiro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("exibir_modulo_financeiro");

                    b.Property<bool>("ExibirNaListaInicialPublica")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("exibir_na_lista_inicial_publica");

                    b.Property<bool>("ExibirNaPesquisaPublica")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("exibir_na_pesquisa_publica");

                    b.Property<bool>("ExibirParticipantesPublicos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("exibir_participantes_publicos");

                    b.Property<string>("LabelCaptura")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("label_captura");

                    b.Property<string>("LabelCapturaPlural")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("label_captura_plural");

                    b.Property<string>("LabelEquipe")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("label_equipe");

                    b.Property<string>("LabelEquipePlural")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("label_equipe_plural");

                    b.Property<string>("LabelItem")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("label_item");

                    b.Property<string>("LabelItemPlural")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("label_item_plural");

                    b.Property<string>("LabelMembro")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("label_membro");

                    b.Property<string>("LabelMembroPlural")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("label_membro_plural");

                    b.Property<string>("LabelSupervisor")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("label_supervisor");

                    b.Property<string>("LabelSupervisorPlural")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("label_supervisor_plural");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("logo_url");

                    b.Property<string>("MedidaCaptura")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("medida_captura");

                    b.Property<int>("ModoSorteio")
                        .HasColumnType("integer")
                        .HasColumnName("modo_sorteio");

                    b.Property<string>("NomeTorneio")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome_torneio");

                    b.Property<string>("ObservacoesInternas")
                        .HasColumnType("text")
                        .HasColumnName("observacoes_internas");

                    b.Property<bool>("PermitirCapturaOffline")
                        .HasColumnType("boolean")
                        .HasColumnName("permitir_captura_offline");

                    b.Property<bool>("PermitirRegistroPublicoMembro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("permitir_registro_publico_membro");

                    b.Property<bool>("PremiacaoPorEquipe")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("premiacao_por_equipe");

                    b.Property<bool>("PremiacaoPorMembro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("premiacao_por_membro");

                    b.Property<int>("QtdGanhadores")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(3)
                        .HasColumnName("qtd_ganhadores");

                    b.Property<int>("QuantidadeParcelas")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("quantidade_parcelas");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("slug");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<decimal>("TaxaInscricaoValor")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("taxa_inscricao_valor");

                    b.Property<int>("TipoTorneio")
                        .HasColumnType("integer")
                        .HasColumnName("tipo_torneio");

                    b.Property<bool>("UsarFatorMultiplicador")
                        .HasColumnType("boolean")
                        .HasColumnName("usar_fator_multiplicador");

                    b.Property<decimal>("ValorPorMembro")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("valor_por_membro");

                    b.HasKey("Id")
                        .HasName("pk_torneio");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_torneio_slug");

                    b.ToTable("torneio", (string)null);
                });

            modelBuilder.Entity("Torneio.Domain.Entities.ValorParcelaTorneio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("NumeroParcela")
                        .HasColumnType("integer")
                        .HasColumnName("numero_parcela");

                    b.Property<Guid>("TorneioId")
                        .HasColumnType("uuid")
                        .HasColumnName("torneio_id");

                    b.Property<decimal>("Valor")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("valor");

                    b.HasKey("Id")
                        .HasName("pk_valores_parcelas_torneio");

                    b.HasIndex("TorneioId", "NumeroParcela")
                        .IsUnique()
                        .HasDatabaseName("ix_valores_parcelas_torneio_torneio_id_numero_parcela");

                    b.ToTable("valores_parcelas_torneio", (string)null);
                });

            modelBuilder.Entity("equipe_membro", b =>
                {
                    b.Property<Guid>("EquipeId")
                        .HasColumnType("uuid")
                        .HasColumnName("equipe_id");

                    b.Property<Guid>("MembrosId")
                        .HasColumnType("uuid")
                        .HasColumnName("membros_id");

                    b.HasKey("EquipeId", "MembrosId")
                        .HasName("pk_equipe_membro");

                    b.HasIndex("MembrosId")
                        .HasDatabaseName("ix_equipe_membro_membros_id");

                    b.ToTable("equipe_membro", (string)null);
                });

            modelBuilder.Entity("Torneio.Domain.Entities.AdminTorneio", b =>
                {
                    b.HasOne("Torneio.Domain.Entities.TorneioEntity", null)
                        .WithMany()
                        .HasForeignKey("TorneioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_admins_torneio_torneiros_torneio_id");
                });

            modelBuilder.Entity("Torneio.Domain.Entities.Banner", b =>
                {
                    b.HasOne("Torneio.Domain.Entities.TorneioEntity", "Torneio")
                        .WithMany()
                        .HasForeignKey("TorneioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_banners_torneiros_torneio_id");

                    b.Navigation("Torneio");
                });

            modelBuilder.Entity("Torneio.Domain.Entities.Captura", b =>
                {
                    b.HasOne("Torneio.Domain.Entities.Equipe", null)
                        .WithMany()
                        .HasForeignKey("EquipeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_capturas_equipes_equipe_id");

                    b.HasOne("Torneio.Domain.Entities.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_capturas_itens_item_id");

                    b.HasOne("Torneio.Domain.Entities.Membro", null)
                        .WithMany()
                        .HasForeignKey("MembroId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_capturas_membros_membro_id");

                    b.HasOne("Torneio.Domain.Entities.TorneioEntity", null)
                        .WithMany()
                        .HasForeignKey("TorneioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_capturas_torneiros_torneio_id");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("Torneio.Domain.Entities.Equipe", b =>
                {
                    b.HasOne("Torneio.Domain.Entities.TorneioEntity", null)
                        .WithMany()
                        .HasForeignKey("TorneioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_equipes_torneiros_torneio_id");
                });

            modelBuilder.Entity("Torneio.Domain.Entities.Fiscal", b =>
                {
                    b.HasOne("Torneio.Domain.Entities.TorneioEntity", null)
                        .WithMany()
                        .HasForeignKey("TorneioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_fiscais_torneiros_torneio_id");
                });

            modelBuilder.Entity("Torneio.Domain.Entities.FiscalEquipe", b =>
                {
                    b.HasOne("Torneio.Domain.Entities.Equipe", "Equipe")
                        .WithMany("Fiscais")
                        .HasForeignKey("EquipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_fiscal_equipe_equipes_equipe_id");

                    b.HasOne("Torneio.Domain.Entities.Fiscal", "Fiscal")
                        .WithMany("Equipes")
                        .HasForeignKey("FiscalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_fiscal_equipe_fiscais_fiscal_id");

                    b.Navigation("Equipe");

                    b.Navigation("Fiscal");
                });

            modelBuilder.Entity("Torneio.Domain.Entities.Grupo", b =>
                {
                    b.HasOne("Torneio.Domain.Entities.TorneioEntity", null)
                        .WithMany()
                        .HasForeignKey("TorneioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_grupos_torneiros_torneio_id");
                });

            modelBuilder.Entity("Torneio.Domain.Entities.GrupoMembro", b =>
                {
                    b.HasOne("Torneio.Domain.Entities.Grupo", null)
                        .WithMany("Membros")
                        .HasForeignKey("GrupoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_grupos_membros_grupos_grupo_id");

                    b.HasOne("Torneio.Domain.Entities.Membro", "Membro")
                        .WithMany()
                        .HasForeignKey("MembroId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_grupos_membros_membros_membro_id");

                    b.Navigation("Membro");
                });

            modelBuilder.Entity("Torneio.Domain.Entities.Item", b =>
                {
                    b.HasOne("Torneio.Domain.Entities.EspeciePeixe", "Especie")
                        .WithMany()
                        .HasForeignKey("EspeciePeixeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_itens_especies_peixe_especie_peixe_id");

                    b.HasOne("Torneio.Domain.Entities.TorneioEntity", null)
                        .WithMany()
                        .HasForeignKey("TorneioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_itens_torneiros_torneio_id");

                    b.Navigation("Especie");
                });

            modelBuilder.Entity("Torneio.Domain.Entities.Membro", b =>
                {
                    b.HasOne("Torneio.Domain.Entities.TorneioEntity", null)
                        .WithMany()
                        .HasForeignKey("TorneioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_membros_torneiros_torneio_id");
                });

            modelBuilder.Entity("Torneio.Domain.Entities.Patrocinador", b =>
                {
                    b.HasOne("Torneio.Domain.Entities.TorneioEntity", null)
                        .WithMany()
                        .HasForeignKey("TorneioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_patrocinadores_torneiros_torneio_id");
                });

            modelBuilder.Entity("Torneio.Domain.Entities.Premio", b =>
                {
                    b.HasOne("Torneio.Domain.Entities.TorneioEntity", null)
                        .WithMany()
                        .HasForeignKey("TorneioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_premios_torneiros_torneio_id");
                });

            modelBuilder.Entity("Torneio.Domain.Entities.ProdutoExtraMembro", b =>
                {
                    b.HasOne("Torneio.Domain.Entities.TorneioEntity", null)
                        .WithMany()
                        .HasForeignKey("TorneioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_produtos_extras_membros_torneiros_torneio_id");
                });

            modelBuilder.Entity("Torneio.Domain.Entities.ProdutoExtraTorneio", b =>
                {
                    b.HasOne("Torneio.Domain.Entities.TorneioEntity", null)
                        .WithMany()
                        .HasForeignKey("TorneioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_produtos_extras_torneio_torneiros_torneio_id");
                });

            modelBuilder.Entity("Torneio.Domain.Entities.SorteioEquipe", b =>
                {
                    b.HasOne("Torneio.Domain.Entities.Equipe", null)
                        .WithMany()
                        .HasForeignKey("EquipeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_sorteios_equipe_equipes_equipe_id");

                    b.HasOne("Torneio.Domain.Entities.Membro", null)
                        .WithMany()
                        .HasForeignKey("MembroId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_sorteios_equipe_membros_membro_id");

                    b.HasOne("Torneio.Domain.Entities.TorneioEntity", null)
                        .WithMany()
                        .HasForeignKey("TorneioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sorteios_equipe_torneiros_torneio_id");
                });

            modelBuilder.Entity("Torneio.Domain.Entities.SorteioGrupo", b =>
                {
                    b.HasOne("Torneio.Domain.Entities.Equipe", null)
                        .WithMany()
                        .HasForeignKey("EquipeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_sorteios_grupo_equipes_equipe_id");

                    b.HasOne("Torneio.Domain.Entities.Grupo", null)
                        .WithMany()
                        .HasForeignKey("GrupoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_sorteios_grupo_grupos_grupo_id");

                    b.HasOne("Torneio.Domain.Entities.TorneioEntity", null)
                        .WithMany()
                        .HasForeignKey("TorneioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sorteios_grupo_torneiros_torneio_id");
                });

            modelBuilder.Entity("equipe_membro", b =>
                {
                    b.HasOne("Torneio.Domain.Entities.Equipe", null)
                        .WithMany()
                        .HasForeignKey("EquipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_equipe_membro_equipes_equipe_id");

                    b.HasOne("Torneio.Domain.Entities.Membro", null)
                        .WithMany()
                        .HasForeignKey("MembrosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_equipe_membro_membros_membros_id");
                });

            modelBuilder.Entity("Torneio.Domain.Entities.Equipe", b =>
                {
                    b.Navigation("Fiscais");
                });

            modelBuilder.Entity("Torneio.Domain.Entities.Fiscal", b =>
                {
                    b.Navigation("Equipes");
                });

            modelBuilder.Entity("Torneio.Domain.Entities.Grupo", b =>
                {
                    b.Navigation("Membros");
                });
#pragma warning restore 612, 618
        }
    }
}
