// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Torneio.Infrastructure.Data;

#nullable disable

namespace Torneio.Infrastructure.Migrations
{
    [DbContext(typeof(TorneioDbContext))]
    [Migration("20260410220254_AddTipoTorneio")]
    partial class AddTipoTorneio
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Torneio.Domain.Entities.AdminGeral", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("senha_hash");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("usuario");

                    b.HasKey("Id")
                        .HasName("pk_admins_geral");

                    b.HasIndex("Usuario")
                        .IsUnique()
                        .HasDatabaseName("ix_admins_geral_usuario");

                    b.ToTable("admins_geral", (string)null);
                });

            modelBuilder.Entity("Torneio.Domain.Entities.AdminTorneio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("senha_hash");

                    b.Property<Guid>("TorneioId")
                        .HasColumnType("uuid")
                        .HasColumnName("torneio_id");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("usuario");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("pk_admins_torneio");

                    b.HasIndex("TorneioId")
                        .HasDatabaseName("ix_admins_torneio_torneio_id");

                    b.HasIndex("Usuario", "TorneioId")
                        .IsUnique()
                        .HasDatabaseName("ix_admins_torneio_usuario_torneio_id");

                    b.ToTable("admins_torneio", (string)null);
                });

            modelBuilder.Entity("Torneio.Domain.Entities.AnoTorneio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Ano")
                        .HasColumnType("integer")
                        .HasColumnName("ano");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid>("TorneioId")
                        .HasColumnType("uuid")
                        .HasColumnName("torneio_id");

                    b.HasKey("Id")
                        .HasName("pk_anos_torneio");

                    b.HasIndex("TorneioId", "Ano")
                        .IsUnique()
                        .HasDatabaseName("ix_anos_torneio_torneio_id_ano");

                    b.ToTable("anos_torneio", (string)null);
                });

            modelBuilder.Entity("Torneio.Domain.Entities.Captura", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AnoTorneioId")
                        .HasColumnType("uuid")
                        .HasColumnName("ano_torneio_id");

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_hora");

                    b.Property<Guid>("EquipeId")
                        .HasColumnType("uuid")
                        .HasColumnName("equipe_id");

                    b.Property<string>("FotoUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("foto_url");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("item_id");

                    b.Property<Guid>("MembroId")
                        .HasColumnType("uuid")
                        .HasColumnName("membro_id");

                    b.Property<bool>("PendenteSync")
                        .HasColumnType("boolean")
                        .HasColumnName("pendente_sync");

                    b.Property<decimal>("TamanhoMedida")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("tamanho_medida");

                    b.Property<Guid>("TorneioId")
                        .HasColumnType("uuid")
                        .HasColumnName("torneio_id");

                    b.HasKey("Id")
                        .HasName("pk_capturas");

                    b.HasIndex("EquipeId")
                        .HasDatabaseName("ix_capturas_equipe_id");

                    b.HasIndex("ItemId")
                        .HasDatabaseName("ix_capturas_item_id");

                    b.HasIndex("MembroId")
                        .HasDatabaseName("ix_capturas_membro_id");

                    b.HasIndex("PendenteSync")
                        .HasDatabaseName("ix_capturas_pendente_sync");

                    b.HasIndex("TorneioId")
                        .HasDatabaseName("ix_capturas_torneio_id");

                    b.HasIndex("AnoTorneioId", "EquipeId")
                        .HasDatabaseName("ix_capturas_ano_torneio_id_equipe_id");

                    b.HasIndex("AnoTorneioId", "MembroId")
                        .HasDatabaseName("ix_capturas_ano_torneio_id_membro_id");

                    b.ToTable("capturas", (string)null);
                });

            modelBuilder.Entity("Torneio.Domain.Entities.Equipe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AnoTorneioId")
                        .HasColumnType("uuid")
                        .HasColumnName("ano_torneio_id");

                    b.Property<string>("Capitao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("capitao");

                    b.Property<Guid>("FiscalId")
                        .HasColumnType("uuid")
                        .HasColumnName("fiscal_id");

                    b.Property<string>("FotoCapitaoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("foto_capitao_url");

                    b.Property<string>("FotoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("foto_url");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome");

                    b.Property<int>("QtdVagas")
                        .HasColumnType("integer")
                        .HasColumnName("qtd_vagas");

                    b.Property<Guid>("TorneioId")
                        .HasColumnType("uuid")
                        .HasColumnName("torneio_id");

                    b.HasKey("Id")
                        .HasName("pk_equipes");

                    b.HasIndex("AnoTorneioId")
                        .HasDatabaseName("ix_equipes_ano_torneio_id");

                    b.HasIndex("FiscalId")
                        .HasDatabaseName("ix_equipes_fiscal_id");

                    b.HasIndex("TorneioId")
                        .HasDatabaseName("ix_equipes_torneio_id");

                    b.ToTable("equipes", (string)null);
                });

            modelBuilder.Entity("Torneio.Domain.Entities.Fiscal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AnoTorneioId")
                        .HasColumnType("uuid")
                        .HasColumnName("ano_torneio_id");

                    b.Property<string>("FotoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("foto_url");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("senha_hash");

                    b.Property<Guid>("TorneioId")
                        .HasColumnType("uuid")
                        .HasColumnName("torneio_id");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("usuario");

                    b.HasKey("Id")
                        .HasName("pk_fiscais");

                    b.HasIndex("AnoTorneioId")
                        .HasDatabaseName("ix_fiscais_ano_torneio_id");

                    b.HasIndex("TorneioId")
                        .HasDatabaseName("ix_fiscais_torneio_id");

                    b.HasIndex("Usuario", "TorneioId")
                        .IsUnique()
                        .HasDatabaseName("ix_fiscais_usuario_torneio_id");

                    b.ToTable("fiscais", (string)null);
                });

            modelBuilder.Entity("Torneio.Domain.Entities.Item", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Comprimento")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("comprimento");

                    b.Property<decimal>("FatorMultiplicador")
                        .HasColumnType("numeric(10,4)")
                        .HasColumnName("fator_multiplicador");

                    b.Property<string>("FotoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("foto_url");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome");

                    b.Property<Guid>("TorneioId")
                        .HasColumnType("uuid")
                        .HasColumnName("torneio_id");

                    b.HasKey("Id")
                        .HasName("pk_itens");

                    b.HasIndex("TorneioId")
                        .HasDatabaseName("ix_itens_torneio_id");

                    b.ToTable("itens", (string)null);
                });

            modelBuilder.Entity("Torneio.Domain.Entities.Membro", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AnoTorneioId")
                        .HasColumnType("uuid")
                        .HasColumnName("ano_torneio_id");

                    b.Property<string>("FotoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("foto_url");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome");

                    b.Property<Guid>("TorneioId")
                        .HasColumnType("uuid")
                        .HasColumnName("torneio_id");

                    b.HasKey("Id")
                        .HasName("pk_membros");

                    b.HasIndex("AnoTorneioId")
                        .HasDatabaseName("ix_membros_ano_torneio_id");

                    b.HasIndex("TorneioId")
                        .HasDatabaseName("ix_membros_torneio_id");

                    b.ToTable("membros", (string)null);
                });

            modelBuilder.Entity("Torneio.Domain.Entities.SorteioEquipe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AnoTorneioId")
                        .HasColumnType("uuid")
                        .HasColumnName("ano_torneio_id");

                    b.Property<Guid>("EquipeId")
                        .HasColumnType("uuid")
                        .HasColumnName("equipe_id");

                    b.Property<Guid>("MembroId")
                        .HasColumnType("uuid")
                        .HasColumnName("membro_id");

                    b.Property<int>("Posicao")
                        .HasColumnType("integer")
                        .HasColumnName("posicao");

                    b.Property<Guid>("TorneioId")
                        .HasColumnType("uuid")
                        .HasColumnName("torneio_id");

                    b.HasKey("Id")
                        .HasName("pk_sorteios_equipe");

                    b.HasIndex("EquipeId")
                        .HasDatabaseName("ix_sorteios_equipe_equipe_id");

                    b.HasIndex("MembroId")
                        .HasDatabaseName("ix_sorteios_equipe_membro_id");

                    b.HasIndex("TorneioId")
                        .HasDatabaseName("ix_sorteios_equipe_torneio_id");

                    b.HasIndex("AnoTorneioId", "EquipeId")
                        .IsUnique()
                        .HasDatabaseName("ix_sorteios_equipe_ano_torneio_id_equipe_id");

                    b.HasIndex("AnoTorneioId", "Posicao")
                        .IsUnique()
                        .HasDatabaseName("ix_sorteios_equipe_ano_torneio_id_posicao");

                    b.ToTable("sorteios_equipe", (string)null);
                });

            modelBuilder.Entity("Torneio.Domain.Entities.TorneioEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<string>("LabelCaptura")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("label_captura");

                    b.Property<string>("LabelEquipe")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("label_equipe");

                    b.Property<string>("LabelItem")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("label_item");

                    b.Property<string>("LabelMembro")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("label_membro");

                    b.Property<string>("LabelSupervisor")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("label_supervisor");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("logo_url");

                    b.Property<string>("MedidaCaptura")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("medida_captura");

                    b.Property<int>("ModoSorteio")
                        .HasColumnType("integer")
                        .HasColumnName("modo_sorteio");

                    b.Property<string>("NomeTorneio")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome_torneio");

                    b.Property<bool>("PermitirCapturaOffline")
                        .HasColumnType("boolean")
                        .HasColumnName("permitir_captura_offline");

                    b.Property<bool>("PermitirEscolhaManual")
                        .HasColumnType("boolean")
                        .HasColumnName("permitir_escolha_manual");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("slug");

                    b.Property<int>("TipoTorneio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("tipo_torneio");

                    b.Property<bool>("UsarFatorMultiplicador")
                        .HasColumnType("boolean")
                        .HasColumnName("usar_fator_multiplicador");

                    b.HasKey("Id")
                        .HasName("pk_torneio");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_torneio_slug");

                    b.ToTable("torneio", (string)null);
                });

            modelBuilder.Entity("equipe_membro", b =>
                {
                    b.Property<Guid>("EquipeId")
                        .HasColumnType("uuid")
                        .HasColumnName("equipe_id");

                    b.Property<Guid>("MembrosId")
                        .HasColumnType("uuid")
                        .HasColumnName("membros_id");

                    b.HasKey("EquipeId", "MembrosId")
                        .HasName("pk_equipe_membro");

                    b.HasIndex("MembrosId")
                        .HasDatabaseName("ix_equipe_membro_membros_id");

                    b.ToTable("equipe_membro", (string)null);
                });

            modelBuilder.Entity("Torneio.Domain.Entities.AdminTorneio", b =>
                {
                    b.HasOne("Torneio.Domain.Entities.TorneioEntity", null)
                        .WithMany()
                        .HasForeignKey("TorneioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_admins_torneio_torneiros_torneio_id");
                });

            modelBuilder.Entity("Torneio.Domain.Entities.AnoTorneio", b =>
                {
                    b.HasOne("Torneio.Domain.Entities.TorneioEntity", null)
                        .WithMany()
                        .HasForeignKey("TorneioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_anos_torneio_torneiros_torneio_id");
                });

            modelBuilder.Entity("Torneio.Domain.Entities.Captura", b =>
                {
                    b.HasOne("Torneio.Domain.Entities.AnoTorneio", null)
                        .WithMany()
                        .HasForeignKey("AnoTorneioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_capturas_anos_torneio_ano_torneio_id");

                    b.HasOne("Torneio.Domain.Entities.Equipe", null)
                        .WithMany()
                        .HasForeignKey("EquipeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_capturas_equipes_equipe_id");

                    b.HasOne("Torneio.Domain.Entities.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_capturas_itens_item_id");

                    b.HasOne("Torneio.Domain.Entities.Membro", null)
                        .WithMany()
                        .HasForeignKey("MembroId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_capturas_membros_membro_id");

                    b.HasOne("Torneio.Domain.Entities.TorneioEntity", null)
                        .WithMany()
                        .HasForeignKey("TorneioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_capturas_torneiros_torneio_id");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("Torneio.Domain.Entities.Equipe", b =>
                {
                    b.HasOne("Torneio.Domain.Entities.AnoTorneio", null)
                        .WithMany()
                        .HasForeignKey("AnoTorneioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_equipes_anos_torneio_ano_torneio_id");

                    b.HasOne("Torneio.Domain.Entities.Fiscal", null)
                        .WithMany()
                        .HasForeignKey("FiscalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_equipes_fiscais_fiscal_id");

                    b.HasOne("Torneio.Domain.Entities.TorneioEntity", null)
                        .WithMany()
                        .HasForeignKey("TorneioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_equipes_torneiros_torneio_id");
                });

            modelBuilder.Entity("Torneio.Domain.Entities.Fiscal", b =>
                {
                    b.HasOne("Torneio.Domain.Entities.AnoTorneio", null)
                        .WithMany()
                        .HasForeignKey("AnoTorneioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_fiscais_anos_torneio_ano_torneio_id");

                    b.HasOne("Torneio.Domain.Entities.TorneioEntity", null)
                        .WithMany()
                        .HasForeignKey("TorneioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_fiscais_torneiros_torneio_id");
                });

            modelBuilder.Entity("Torneio.Domain.Entities.Item", b =>
                {
                    b.HasOne("Torneio.Domain.Entities.TorneioEntity", null)
                        .WithMany()
                        .HasForeignKey("TorneioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_itens_torneiros_torneio_id");
                });

            modelBuilder.Entity("Torneio.Domain.Entities.Membro", b =>
                {
                    b.HasOne("Torneio.Domain.Entities.AnoTorneio", null)
                        .WithMany()
                        .HasForeignKey("AnoTorneioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_membros_anos_torneio_ano_torneio_id");

                    b.HasOne("Torneio.Domain.Entities.TorneioEntity", null)
                        .WithMany()
                        .HasForeignKey("TorneioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_membros_torneiros_torneio_id");
                });

            modelBuilder.Entity("Torneio.Domain.Entities.SorteioEquipe", b =>
                {
                    b.HasOne("Torneio.Domain.Entities.AnoTorneio", null)
                        .WithMany()
                        .HasForeignKey("AnoTorneioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sorteios_equipe_anos_torneio_ano_torneio_id");

                    b.HasOne("Torneio.Domain.Entities.Equipe", null)
                        .WithMany()
                        .HasForeignKey("EquipeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_sorteios_equipe_equipes_equipe_id");

                    b.HasOne("Torneio.Domain.Entities.Membro", null)
                        .WithMany()
                        .HasForeignKey("MembroId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_sorteios_equipe_membros_membro_id");

                    b.HasOne("Torneio.Domain.Entities.TorneioEntity", null)
                        .WithMany()
                        .HasForeignKey("TorneioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sorteios_equipe_torneiros_torneio_id");
                });

            modelBuilder.Entity("equipe_membro", b =>
                {
                    b.HasOne("Torneio.Domain.Entities.Equipe", null)
                        .WithMany()
                        .HasForeignKey("EquipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_equipe_membro_equipes_equipe_id");

                    b.HasOne("Torneio.Domain.Entities.Membro", null)
                        .WithMany()
                        .HasForeignKey("MembrosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_equipe_membro_membros_membros_id");
                });
#pragma warning restore 612, 618
        }
    }
}
