// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Torneio.Infrastructure.Data;

#nullable disable

namespace Torneio.Infrastructure.Migrations
{
    [DbContext(typeof(TorneioDbContext))]
    [Migration("20260426000000_AddDeveAlterarSenha")]
    partial class AddDeveAlterarSenha
    {
    }
}
