// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Torneio.Infrastructure.Data;

#nullable disable

namespace Torneio.Infrastructure.Migrations
{
    [DbContext(typeof(TorneioDbContext))]
    [Migration("20260423130000_AddBonificacaoParcela")]
    partial class AddBonificacaoParcela
    {
    }
}
